name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

profile: 'personal-bigquery'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  +persist_docs:
      relation: true
      columns: true

models:
  jaffle_shop:
    +persist_docs:
      relation: true
      columns: true
    staging:
      +materialized: view
    marts:
      +materialized: table
